# Generated by Django 4.2.3 on 2023-09-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_libraries_phone_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraries',
            name='leader',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
